In [29]:
import cv2
import numpy as np

In [60]:
# create random value of matrix 5x5
image = np.array([[ 1, 0, 2, 1, 0],
                [0, 2, 3, 0, 1],
                [1, 0, 1, 1, 2],
                [0, 2, 2, 0, 3],
                [0, 4, 1, 2, 0]])

image = image / 5.0

image

array([[0.2, 0. , 0.4, 0.2, 0. ],
       [0. , 0.4, 0.6, 0. , 0.2],
       [0.2, 0. , 0.2, 0.2, 0.4],
       [0. , 0.4, 0.4, 0. , 0.6],
       [0. , 0.8, 0.2, 0.4, 0. ]])

In [61]:
# create kernel 3*3 
kernel = np.array([[-1,0,1],
                   [-1,0,1],
                   [-1,0,1]])

kernel

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [62]:
# create convolution 2D
im2 = cv2.filter2D(src=image, ddepth=-1, kernel=kernel)
im2


array([[ 0. ,  1.4, -0.6, -1.2,  0. ],
       [ 0. ,  0.8,  0. , -0.6,  0. ],
       [ 0. ,  1. , -0.6,  0. ,  0. ],
       [ 0. ,  0.6, -0.6,  0.2,  0. ],
       [ 0. ,  1. , -1.2,  0.2,  0. ]])

In [64]:
im2_int = (im2 * 5).astype(int)
im2_int

array([[ 0,  7, -3, -6,  0],
       [ 0,  4,  0, -3,  0],
       [ 0,  5, -3,  0,  0],
       [ 0,  3, -3,  0,  0],
       [ 0,  5, -6,  0,  0]])

In [65]:
help(cv2.filter2D)

Help on built-in function filter2D:

filter2D(...)
    filter2D(src, ddepth, kernel[, dst[, anchor[, delta[, borderType]]]]) -> dst
    .   @brief Convolves an image with the kernel.
    .   
    .   The function applies an arbitrary linear filter to an image. In-place operation is supported. When
    .   the aperture is partially outside the image, the function interpolates outlier pixel values
    .   according to the specified border mode.
    .   
    .   The function does actually compute correlation, not the convolution:
    .   
    .   \f[\texttt{dst} (x,y) =  \sum _{ \substack{0\leq x' < \texttt{kernel.cols}\\{0\leq y' < \texttt{kernel.rows}}}}  \texttt{kernel} (x',y')* \texttt{src} (x+x'- \texttt{anchor.x} ,y+y'- \texttt{anchor.y} )\f]
    .   
    .   That is, the kernel is not mirrored around the anchor point. If you need a real convolution, flip
    .   the kernel using #flip and set the new anchor to `(kernel.cols - anchor.x - 1, kernel.rows -
    .   anchor.y - 1)`.
    